Feature: Emulate user in nav bot conversation
    In order to quickly deploy a RL agent for content curation
    As a data scientist
    I want to start building a RL agent before significant data has been generated by the homepage bot
    using an emulator that models the environment of a nav bot conversation with a user

    Scenario: Emulate buyer state vector
        Given a new conversation is started
        When the agent is waiting for an utterance
        Then the emulator randomly returns a buyer state vector

    Scenario: Emulate sherlock query
        Given an agent has received a buyer state vector
        When the emulated user is waiting for a response
        Then the emulator randomly returns a set of potential content options

    Scenario: Emulate user response
        Given a buyer state and potential content options
        When the agent selects a potential content option to show the user
        Then the emulator returns the probabilistic reward associated that action
